### ISSUE TITLE
Figure 2 reproduction not quite right

### ISSUE THREAD

**Issue by jeffdlb** [NCAR/cesm-lens-aws#29]
There are a couple of key difference between the original Kay et al. figure 2 and the notebook's reproduction. See attached images. In Notebook version,
* The black "member 1" line does not cover 1850-1920, and does not have a legend.
* The red "observations" line covers 1850-2005 instead of 1920-2005.
* We also don't have the pre-1850 control period, but that's less critical than what appears to be something not correctly plotted.

![kay-et-al-2015 fig2](https://user-images.githubusercontent.com/4967282/70396486-462c2400-19be-11ea-9a88-53ea4e565731.jpeg)
![KayEtalFig2_notebook](https://user-images.githubusercontent.com/4967282/70396489-547a4000-19be-11ea-92c1-a3dfabf2dde5.png)

**Comment by bonnland** [comment]
@jeffdlb  Should our reproduction of this Figure be limited to members 1-30, as in the original, or is there some value to plotting all 40 members?

**Comment by jeffdlb** [comment]
I think if we're claiming it reproduces we should have it match as closely as possible for this particular notebook. A separate analysis with all 40 members might have some scientific value, however.

**Comment by jeffdlb** [comment]
That being said, we already show all members and it doesn't change the
figure much, do keeping as-is is fine. Bigger issue is the red and black
lines.

**Comment by bonnland** [comment]
I will try to get to it later today.

**Comment by jeffdlb** [comment]
If it looks like a non-obvious, multi-hour fix we should discuss first.

**Comment by bonnland** [comment]
I didn't get it completely done, but it looks do-able without too much effort.   It's necessary to load the "HIST" experiment, creating three Xarray datasets instead of two.   The "HIST" experiment appears to have a single ensemble member with monthly data frequency, which means repeating the patterns we see for creating t_20c_ts, t_ref_ts, etc. with some tweaks.

**Comment by bonnland** [comment]
Here is a binder link that has my current changes.   Note that these are still a work in progress, and could contain missing code or typos:

https://aws-uswest2-binder.pangeo.io/v2/gh/bonnland/cesm-lens-aws/fix-figure2?urlpath=lab

I had to create by painstakingly copy-pasting from a notebook running on AWS, which is error-prone.   

I will test and fix any bugs tommorrow.

**Comment by bonnland** [comment]
I'm unable to run/debug the notebook on AWS right now.   Possibly the load on the Pangeo AWS service is very high, with AGU underway.

**Comment by bonnland** [comment]
@jeffdlb Joe Hamman just added me to the pangeo-data group on GitHub, which gives me access to a persistent AWS environment for modifying the LENS notebooks.   Joe thinks you're also a member.   Here are the steps I took: 

1. Go to https://aws-uswest2.pangeo.io/ and login with your GitHub credentials. 
2. Launch an instance labeled "Latest Pangeo-notebook Image (4 vCPU, 16 Gb)"
3. Open a command-line window in jupyter.
4. Clone your fork of cesm-lens-aws using the command line.   This folder structure should be reveled in the jupyter folder interface.
5. Click on folders to navigate to the LENS notebook and open it.   Any changes you save here can be commited and pushed back to your fork on GitHub.
