### ISSUE TITLE
Intake-esm with long names

### ISSUE THREAD

**Issue by jeffdlb** [NCAR/cesm-lens-aws#30]
I just uploaded 2 files that include CESM long names in the intake-esm catalog:
https://ncar-cesm-lens.s3.us-west-2.amazonaws.com/catalogs/aws-cesm1-le-longNames.json
https://ncar-cesm-lens.s3.us-west-2.amazonaws.com/catalogs/aws-cesm1-le-longNames.csv

I have not had a chance to test in a Notebook yet, but wanted to let people know in case someone wanted to try it. 

-Jeff DLB

**Comment by andersy005** [comment]
For better user experience, can we remove the spaces in the long_name column?

i.e . `Net longwave flux at surface` ---> `Net_longwave_flux_at_surface`

**Comment by andersy005** [comment]
Removing spaces would allow avoiding typos and other subtle errors when the user wants to use the `long_name` column in the `search()` method.

**Comment by jeffdlb** [comment]
Yes, but would rather in that case use the actual CF Standard Names (with
underscores). Need to determine the correct mapping...

-Jeff
