### ISSUE TITLE
Binder is broken?

### ISSUE THREAD

**Issue by rabernat** [NCAR/cesm-lens-aws#40]
Following the binder link on the Readme:
https://aws-uswest2-binder.pangeo.io/v2/gh/NCAR/cesm-lens-aws/master?urlpath=lab
I cannot get the build to start, let alone complete. Is there some problem with the aws binder?

**Comment by andersy005** [comment]
Cc @scottyhq in case he has suggestions on how to address this issue.

**Comment by scottyhq** [comment]
binder is working as far as I know, so maybe there is an issue with the new build? I see this message on the logs 
```
[ec2-user@ip-192-168-60-131 pangeo-binder]$ kubectl logs jupyter-ncar-2dcesm-2dlens-2daws-2dmpafv5s7 -n binder-staging
Error from server (BadRequest): container "notebook" in pod "jupyter-ncar-2dcesm-2dlens-2daws-2dmpafv5s7" is waiting to start: trying and failing to pull image
```

Note that built images are here:
https://hub.docker.com/repository/docker/pangeoaccess/binder-stagingncar-2dcesm-2dlens-2daws-82a8c0 

There likely will be some down-time related to updating this repo with both the GCE and AWS binder config
https://github.com/pangeo-data/pangeo-binder/issues/122
https://github.com/pangeo-data/pangeo-binder/issues/120

**Comment by andersy005** [comment]
Closing....
