### ISSUE TITLE
Change non ocean data to match ocean data

### ISSUE THREAD

**Issue by andersy005** [NCAR/cesm-lens-aws#54]
As part of #34 we factored out common arrays for the ocean data copied to AWS and put these common arrays into a **grid** zarr store. We need to repeat this process for variables from other components

- [x] cice
- [x] atm
- [x] land

Once all data variables have been updated, the Kay et al. notebook needs to be updated as well.

**Comment by andersy005** [comment]
@jeffdlb, I just noticed that I inadvertently produced and published to S3 more variables than what ywe have listed on the AWS webpage. The extra variables are for the following prefixes:

- atm/hourly6-1990-2005/CESM-LE-*
- atm/hourly6-2026-2035/CESM-LE-*
- atm/hourly6-2071-2080/CESM-LE-*

Let me know if having these extra variables is problematic and I will delete them from AWS S3.

**Comment by jeffdlb** [comment]
Don't delete! We have not used up our allocation so volume is not a
concern. In fact, I think we may be missing some 6-hourly data...

In the atm/hourly6-year1-year2/CESM-LE-* category we claim (
https://doi.org/10.26024/wt24-5j82) to have 2D variables PRECT, PS, PSL,
QREFHT, TREFHT, and TS, and 3D T, U, V, Q, and Z3. However, in
https://s3.console.aws.amazon.com/s3/buckets/ncar-cesm-lens/atm/hourly6-1990-2005/
I
am not seeing PRECT, PS, REFHT, or V, but I am seeing the addition of FLNS
and FSNS. This seems to also be the case for the other two time periods.

-Jeff

**Comment by andersy005** [comment]
> I am not seeing PRECT, PS, REFHT, or V, but I am seeing the addition of FLNS
and FSNS. This seems to also be the case for the other two time periods.

Yeah, I noticed this too... I am currently producing the stores for these variables, and will publish them ASAP.
