### ISSUE TITLE
Update `EnhancedIntakeCatalogDemo.ipynb` notebook?

### ISSUE THREAD

**Issue by andersy005** [NCAR/cesm-lens-aws#59]
@jeffdlb, now that intake-esm supports regular expressions and wildcard expressions, I am wondering if you'd interested in updating the [EnhancedIntakeCatalogDemo.ipynb](https://github.com/NCAR/cesm-lens-aws/blob/master/notebooks/EnhancedIntakeCatalogDemo.ipynb) notebook at some point in the future?

**Comment by jeffdlb** [comment]
Yes, definitely -- not this week, but in September I could do it.

**Comment by andersy005** [comment]
Addressed in #62
