### ISSUE TITLE
Where is the lat/lon data?

### ISSUE THREAD

**Issue by cspencerjones** [NCAR/cesm-lens-aws#61]
I have been using this tutorial to learn to access the CESM data: [http://gallery.pangeo.io/repos/NCAR/cesm-lens-aws/notebooks/EnhancedIntakeCatalogDemo.html](http://gallery.pangeo.io/repos/NCAR/cesm-lens-aws/notebooks/EnhancedIntakeCatalogDemo.html)

It's been really helpful. But the tutorial doesn't tell me how to access latitude and longitude (just nlat, nlon). Can someone point me to that info?

If there are basin masks available somewhere, that would also be really helpful.

**Comment by cspencerjones** [comment]
@andersy005 or @bonnland , could you tell me whether there is a timeline on this? Is it worth me trying to use the lat/lon coordinates from the CMIP6 dataset (which are presumably the same), so that I can move forward?

I realize this issue is in some ways a continuation of #34 but that seems stale and maybe should be closed?

**Comment by andersy005** [comment]
@cspencerjones, 

Thank you for your patience! 

> It's been really helpful. But the tutorial doesn't tell me how to access latitude and longitude (just nlat, nlon). Can someone point me to that info?

As far as I know, `lat`& `lon` values are not output by the model... I've never seen CESM-POP output with `lat` and `lon`. I could be wrong  though... Ccing @mnlevy1981 who knows more about CESM and POP. 

> If there are basin masks available somewhere, that would also be really helpful.

Have you had a chance to look at the `region mask` feature in `pop-tools`
https://pop-tools.readthedocs.io/en/latest/examples/region-mask.html?

**Comment by cspencerjones** [comment]
Amazing! Thanks so much - this is exactly what I wanted to know. It looks as though pop-tools will give me everything I need if I can get it to install on the pangeo workers. I'll look into that. 

Do you (or @mnlevy1981 ) know which pop grid is associated with the CESM-LENS output? e.g. POP_gx1v7, POP_gx1v6? 

Then I will do a PR to the tutorial I am using so that this info is clear to all users.

**Comment by cspencerjones** [comment]
I'm realizing that the grid used to be stored at `'s3://ncar-cesm-lens/ocn/grid.zarr'` https://github.com/NCAR/cesm-lens-aws/issues/34#issuecomment-618365544. I think what I was originally asking is, does this dataset still exist? Because it doesn't seem to be at that path anymore. That would be preferable to the `pop-tools` solution.

**Comment by cspencerjones** [comment]
Sorry to comment more! Apparently what I am looking for is `'s3://ncar-cesm-lens/ocn/static/grid.zarr'`. This solves my issue. I will submit a PR to clarify various docs tomorrow. Thanks for your help.
