### ISSUE TITLE
[Data Request]: UVBOT, VBOT, QBOT, PRECT, TREFMXAV_U, and TREFMNAV_U fields

### ISSUE THREAD

**Issue by zzheng93** [NCAR/cesm-lens-aws#72]
I am using the CESM-LENS-AWS data for my research. However, some of the fields are missing in CESM-LENS-AWS (but they are available in Cheyenne). Could you please upload the following fields to the CESM-LENS-AWS?

"atm", "daily", "rcp85", "from 2006-01-01 to "2100-12-31"
- UBOT 
- VBOT 
- QBOT 
- PRECT

"lnd", "daily", "rcp85", "from 2006-01-01 to 2100-12-31"
- TREFMXAV_U
- TREFMNAV_U  

Thank you!

**Comment by andersy005** [comment]
@zzheng93, the data you requested are now available on AWS and the catalog has been updated:

```python
In [13]: import intake

In [14]: col = intake.open_esm_datastore("https://raw.githubusercontent.com/NCAR/cesm-lens-aws/main/intake-catalogs/aws-cesm1-le.json")

In [15]: col.search(variable=['UBOT', 'VBOT', 'QBOT', 'PRECT', 'TREFMXAV_U', 'TREFMNAV_U'], frequency='daily').df
Out[15]:
     variable                                          long_name component experiment  ...  units           start_time             end_time                                               path
0       PRECT  total (convective and large-scale) precipitati...       atm        20C  ...    m/s  1920-01-01 12:00:00  2005-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-20C-PRECT...
1        UBOT                      lowest model level zonal wind       atm        20C  ...    m/s  1920-01-01 12:00:00  2005-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-20C-UBOT....
2       PRECT  total (convective and large-scale) precipitati...       atm       HIST  ...    m/s  1850-01-01 12:00:00  1919-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-HIST-PREC...
3        UBOT                      lowest model level zonal wind       atm       HIST  ...    m/s  1850-01-01 12:00:00  1919-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-HIST-UBOT...
4       PRECT  total (convective and large-scale) precipitati...       atm      RCP85  ...    m/s  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-PRE...
5        QBOT        lowest model level water vapor mixing ratio       atm      RCP85  ...  kg/kg  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-QBO...
6        UBOT                      lowest model level zonal wind       atm      RCP85  ...    m/s  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-UBO...
7        VBOT                 lowest model level meridional wind       atm      RCP85  ...    m/s  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-VBO...
8  TREFMNAV_U     urban daily minimum of average 2-m temperature       lnd      RCP85  ...      K  2006-01-01 12:00:00  2101-01-01 12:00:00  s3://ncar-cesm-lens/lnd/daily/cesmLE-RCP85-TRE...
9  TREFMXAV_U     urban daily maximum of average 2-m temperature       lnd      RCP85  ...      K  2006-01-01 12:00:00  2101-01-01 12:00:00  s3://ncar-cesm-lens/lnd/daily/cesmLE-RCP85-TRE...

```


Please reopen if you encounter issues with the data and/or catalog. 

Thank you!

**Comment by jeffdlb** [comment]
Thank you, Anderson!

-Jeff DLB

Jeff de La Beaujardiere, PhD
Director, NCAR/CISL Information Systems Division
https://staff.ucar.edu/users/jeffdlb
https://orcid.org/0000-0002-1001-9210

**Comment by zzheng93** [comment]
> @zzheng93, the data you requested are now available on AWS and the catalog has been updated:
> 
> ```python
> In [13]: import intake
> 
> In [14]: col = intake.open_esm_datastore("https://raw.githubusercontent.com/NCAR/cesm-lens-aws/main/intake-catalogs/aws-cesm1-le.json")
> 
> In [15]: col.search(variable=['UBOT', 'VBOT', 'QBOT', 'PRECT', 'TREFMXAV_U', 'TREFMNAV_U'], frequency='daily').df
> Out[15]:
>      variable                                          long_name component experiment  ...  units           start_time             end_time                                               path
> 0       PRECT  total (convective and large-scale) precipitati...       atm        20C  ...    m/s  1920-01-01 12:00:00  2005-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-20C-PRECT...
> 1        UBOT                      lowest model level zonal wind       atm        20C  ...    m/s  1920-01-01 12:00:00  2005-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-20C-UBOT....
> 2       PRECT  total (convective and large-scale) precipitati...       atm       HIST  ...    m/s  1850-01-01 12:00:00  1919-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-HIST-PREC...
> 3        UBOT                      lowest model level zonal wind       atm       HIST  ...    m/s  1850-01-01 12:00:00  1919-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-HIST-UBOT...
> 4       PRECT  total (convective and large-scale) precipitati...       atm      RCP85  ...    m/s  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-PRE...
> 5        QBOT        lowest model level water vapor mixing ratio       atm      RCP85  ...  kg/kg  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-QBO...
> 6        UBOT                      lowest model level zonal wind       atm      RCP85  ...    m/s  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-UBO...
> 7        VBOT                 lowest model level meridional wind       atm      RCP85  ...    m/s  2006-01-01 12:00:00  2100-12-31 12:00:00  s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-VBO...
> 8  TREFMNAV_U     urban daily minimum of average 2-m temperature       lnd      RCP85  ...      K  2006-01-01 12:00:00  2101-01-01 12:00:00  s3://ncar-cesm-lens/lnd/daily/cesmLE-RCP85-TRE...
> 9  TREFMXAV_U     urban daily maximum of average 2-m temperature       lnd      RCP85  ...      K  2006-01-01 12:00:00  2101-01-01 12:00:00  s3://ncar-cesm-lens/lnd/daily/cesmLE-RCP85-TRE...
> ```
> 
> Please reopen if you encounter issues with the data and/or catalog.
> 
> Thank you!

Thank you very much, Anderson!
